CREATE SEQUENCE seq
 START WITH     1000
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;

commit;

-------- WHEEL --------
INSERT INTO WHEEL (RECORD_ID,START_DATE,PRICE,END_DATE,TYPE)
VALUES (seq.nextval, to_date('20-SEP-2017','DD-MON-YYYY'), 2000, to_date('20-SEP-2018','DD-MON-YYYY'), 'TUBELESS');

INSERT INTO WHEEL (RECORD_ID,START_DATE,PRICE,END_DATE,TYPE)
VALUES (seq.nextval, to_date('20-SEP-2018','DD-MON-YYYY'), 2200, to_date('20-SEP-2019','DD-MON-YYYY'), 'TUBELESS');

INSERT INTO WHEEL (RECORD_ID,START_DATE,PRICE,END_DATE,TYPE)
VALUES (seq.nextval, to_date('20-SEP-2017','DD-MON-YYYY'), 1500, to_date('20-SEP-2018','DD-MON-YYYY'), 'TUBE');

INSERT INTO WHEEL (RECORD_ID,START_DATE,PRICE,END_DATE,TYPE)
VALUES (seq.nextval, to_date('20-SEP-2018','DD-MON-YYYY'), 1800, to_date('20-SEP-2019','DD-MON-YYYY'), 'TUBE');

-------- CHAIN_ASSEMBLY --------

INSERT INTO CHAIN_ASSEMBLY (RECORD_ID,START_DATE,PRICE,END_DATE,TYPE)
VALUES (seq.nextval, to_date('20-SEP-2017','DD-MON-YYYY'), 3300, to_date('20-SEP-2018','DD-MON-YYYY'), 'ONE-SPEED');

INSERT INTO CHAIN_ASSEMBLY (RECORD_ID,START_DATE,PRICE,END_DATE,TYPE)
VALUES (seq.nextval, to_date('20-SEP-2018','DD-MON-YYYY'), 3500, to_date('20-SEP-2019','DD-MON-YYYY'), 'ONE-SPEED');

INSERT INTO CHAIN_ASSEMBLY (RECORD_ID,START_DATE,PRICE,END_DATE,TYPE)
VALUES (seq.nextval, to_date('20-SEP-2017','DD-MON-YYYY'), 4000, to_date('20-SEP-2018','DD-MON-YYYY'), 'DERAILLEUR');

INSERT INTO CHAIN_ASSEMBLY (RECORD_ID,START_DATE,PRICE,END_DATE,TYPE)
VALUES (seq.nextval, to_date('20-SEP-2018','DD-MON-YYYY'), 4200, to_date('20-SEP-2019','DD-MON-YYYY'), 'DERAILLEUR');

-------- FRAME --------

INSERT INTO FRAME (RECORD_ID,START_DATE,PRICE,END_DATE,TYPE)
VALUES (seq.nextval, to_date('20-SEP-2017','DD-MON-YYYY'), 6000, to_date('20-SEP-2018','DD-MON-YYYY'), 'DIAMOND');

INSERT INTO FRAME (RECORD_ID,START_DATE,PRICE,END_DATE,TYPE)
VALUES (seq.nextval, to_date('20-SEP-2018','DD-MON-YYYY'), 7000, to_date('20-SEP-2019','DD-MON-YYYY'), 'DIAMOND');

INSERT INTO FRAME (RECORD_ID,START_DATE,PRICE,END_DATE,TYPE)
VALUES (seq.nextval, to_date('20-SEP-2017','DD-MON-YYYY'), 5000, to_date('20-SEP-2018','DD-MON-YYYY'), 'CROSS');

INSERT INTO FRAME (RECORD_ID,START_DATE,PRICE,END_DATE,TYPE)
VALUES (seq.nextval, to_date('20-SEP-2018','DD-MON-YYYY'), 5500, to_date('20-SEP-2019','DD-MON-YYYY'), 'CROSS');

-------- SEAT --------

INSERT INTO SEAT (RECORD_ID,START_DATE,PRICE,END_DATE,TYPE)
VALUES (seq.nextval, to_date('20-SEP-2017','DD-MON-YYYY'), 600, to_date('20-SEP-2018','DD-MON-YYYY'), 'WIDE');

INSERT INTO SEAT (RECORD_ID,START_DATE,PRICE,END_DATE,TYPE)
VALUES (seq.nextval, to_date('20-SEP-2018','DD-MON-YYYY'), 650, to_date('20-SEP-2019','DD-MON-YYYY'), 'WIDE');

INSERT INTO SEAT (RECORD_ID,START_DATE,PRICE,END_DATE,TYPE)
VALUES (seq.nextval, to_date('20-SEP-2017','DD-MON-YYYY'), 300, to_date('20-SEP-2018','DD-MON-YYYY'), 'THIN');

INSERT INTO SEAT (RECORD_ID,START_DATE,PRICE,END_DATE,TYPE)
VALUES (seq.nextval, to_date('20-SEP-2018','DD-MON-YYYY'), 350, to_date('20-SEP-2019','DD-MON-YYYY'), 'THIN');


commit


